name: Generate Snake

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: theskinnyhippo
          outputs: dist/snake.svg

      - name: Commit Snakes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add -A
          git commit -m "Generated Snake" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

